/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hw2network2part2;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.google.gson.JsonSyntaxException;
import java.io.BufferedWriter;
import java.io.DataInputStream;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.RandomAccessFile;
import java.lang.reflect.Array;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.json.JSONArray;
import org.json.JSONObject;
/**
 *
 * @author hp
 */

public class HW_JFrame extends javax.swing.JFrame {
int flagVerfiy1 = 0;
int flagVerfiy2 = 0;

    /**
     * Creates new form HW_JFrame
     */
    public HW_JFrame() {
        initComponents();
        this.systemButton.setEnabled(false);
        this.arpButton.setEnabled(false);
        this.udpButton.setEnabled(false);
        this.tcpButton.setEnabled(false);

        this.updateButton.setEnabled(false);
        this.sysContactText.setEnabled(false);
        this.sysNameText.setEnabled(false);
        this.sysLocationText.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        IdText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        usernameText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordText = new javax.swing.JTextField();
        verfiy1Button = new javax.swing.JButton();
        verfiy2Button = new javax.swing.JButton();
        systemButton = new javax.swing.JButton();
        udpButton = new javax.swing.JButton();
        arpButton = new javax.swing.JButton();
        tcpButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sysContactText = new javax.swing.JTextField();
        sysNameText = new javax.swing.JTextField();
        sysLocationText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        stateOfVerfiy1 = new javax.swing.JLabel();
        stateOfVerfiy2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID");

        IdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdTextActionPerformed(evt);
            }
        });

        jLabel2.setText("UserName");

        usernameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextActionPerformed(evt);
            }
        });

        jLabel3.setText("Password");

        passwordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextActionPerformed(evt);
            }
        });

        verfiy1Button.setText("Verfiy1");
        verfiy1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verfiy1ButtonActionPerformed(evt);
            }
        });

        verfiy2Button.setText("Verfiy2");
        verfiy2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verfiy2ButtonActionPerformed(evt);
            }
        });

        systemButton.setText("System");
        systemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                systemButtonActionPerformed(evt);
            }
        });

        udpButton.setText("UDP");
        udpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                udpButtonActionPerformed(evt);
            }
        });

        arpButton.setText("ARP");
        arpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arpButtonActionPerformed(evt);
            }
        });

        tcpButton.setText("TCP");
        tcpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcpButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("sysContact");

        jLabel5.setText("sysName");

        jLabel6.setText("sysLocation");

        sysContactText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sysContactTextActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Cormorant Infant SemiBold", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setText("Welcome to the SNMP and HTTP application");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel8.setFont(new java.awt.Font("Cormorant Infant SemiBold", 1, 14)); // NOI18N
        jLabel8.setText("SNMP ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stateOfVerfiy1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(IdText, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(usernameText, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(sysContactText, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(sysNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(verfiy1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(202, 202, 202)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(sysLocationText, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(60, 60, 60)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(117, 117, 117)
                                        .addComponent(jLabel7)))
                                .addGap(0, 31, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tcpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(arpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(udpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(systemButton, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(verfiy2Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stateOfVerfiy2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verfiy1Button)
                    .addComponent(verfiy2Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(stateOfVerfiy2, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                    .addComponent(stateOfVerfiy1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(systemButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(udpButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(arpButton)
                        .addGap(18, 18, 18)
                        .addComponent(tcpButton))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sysContactText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sysNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sysLocationText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdTextActionPerformed

    private void usernameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextActionPerformed

    private void passwordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTextActionPerformed

    private void verfiy1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verfiy1ButtonActionPerformed
        // TODO add your handling code here:
        sendData_GET(1);
        
    }//GEN-LAST:event_verfiy1ButtonActionPerformed

    private void verfiy2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verfiy2ButtonActionPerformed
        sendData_GET(2);
        

        // TODO add your handling code here:
    }//GEN-LAST:event_verfiy2ButtonActionPerformed

    private void sysContactTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sysContactTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sysContactTextActionPerformed

    private void tcpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcpButtonActionPerformed
        // TODO add your handling code here:
        sendData_GET(4);
    }//GEN-LAST:event_tcpButtonActionPerformed

    private void udpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_udpButtonActionPerformed
        // TODO add your handling code here:
        sendData_GET(3);
    }//GEN-LAST:event_udpButtonActionPerformed

    private void arpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arpButtonActionPerformed
        // TODO add your handling code here:
        sendData_GET(5);
    }//GEN-LAST:event_arpButtonActionPerformed

    private void systemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_systemButtonActionPerformed
        // TODO add your handling code here:
        sendData_GET(6);

    }//GEN-LAST:event_systemButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        sendData_GET(7);
        // TODO add your handling code here:
    }//GEN-LAST:event_updateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
     void sendData_GET(int verify) {
         
        DataInputStream send;
        String id=this.IdText.getText();
        String Name = this.usernameText.getText();
        String Password = this.passwordText.getText();
        String sysContact = this.sysContactText.getText();
        String sysName =  this.sysNameText.getText();
        String sysLocation = this.sysLocationText.getText();
        this.updateButton.setEnabled(false);
        this.sysContactText.setEnabled(false);
        this.sysNameText.setEnabled(false);
        this.sysLocationText.setEnabled(false);
        try {
            String str="";
            if(verify==2)
                str = "http://localhost:8085/server/jspPage.jsp?Name="+Name+"&Password="+Password;
            else if(verify==1)
//                D:\University\University_materials\Fourth Year\First Semester\Network 2\HW2\SNMP-HTTP\server\test\nServlet.java
                str = "http://localhost:8085/server/nServlet?id="+id+"&Password="+Password;
            else if(verify==3)
                str = "http://localhost/SNMP_Project/server/UDP_Info.php";
            else if(verify==4)
                str = "http://localhost/SNMP_Project/server/TCP_info.php";
            else if(verify==5)
                str = "http://localhost/SNMP_Project/server/ARP_Info.php";
            else if(verify==6){
                str = "http://localhost/SNMP_Project/server/System_Info.php";
            }
            else if(verify==7)
                str = "http://localhost/SNMP_Project/server/updateData.php?sysContact="+sysContact+"&sysName="+sysName+"&sysLocation="+sysLocation;
            
            URL u = new URL(str);               //+"?"+dataStr 
            //send 
            send = new DataInputStream(u.openConnection().getInputStream());
           
            int temp;
            String state = "";

            HttpURLConnection myConn =(HttpURLConnection) u.openConnection();
            InputStream recive = myConn.getInputStream();
            while ((temp = recive.read()) != -1) {
               
                    state = state + (char) temp;

            }
           
            if(verify ==1)
            {
                this.stateOfVerfiy1.setText(state);
                if(state.trim().equals("Permit"))
                  flagVerfiy1=1;
                else
                    flagVerfiy1=0;
               
            }    
            else if(verify==2)
            {
              this.stateOfVerfiy2.setText(state);
              if(state.trim().equals("Permit"))
                  flagVerfiy2=1;
              else 
                  flagVerfiy2=0;
            }
            
            
            if(flagVerfiy2==1 && flagVerfiy1==1)
            {
                this.systemButton.setEnabled(true);
                this.arpButton.setEnabled(true);
                this.udpButton.setEnabled(true);
                this.tcpButton.setEnabled(true);
                if(verify==3)
                {
                    String res="";
                    res+="#             IPADDRESS             PORT\n";
                    JSONObject jo = new JSONObject("{'0':"+state+"}");
                    JSONArray array = jo.getJSONArray("0");
                    ArrayList<Object> listdata = new ArrayList<Object>();  
                if (array != null) {   

                    //Iterating JSON array  
                    for (int i=0;i<array.length();i++){   
                        //Adding each element of JSON array into ArrayList  
                        listdata.add(array.get(i));  
                    }   
                }  
                    this.jTextArea1.setText(""+listdata.get(0));

                }
                else if(verify==3 || verify==4||verify==5)
                {
                    this.jTextArea1.setText(state);
                }
                else if(verify==6)
                {
                    this.updateButton.setEnabled(true);
                    this.sysContactText.setEnabled(true);
                    this.sysNameText.setEnabled(true);
                    this.sysLocationText.setEnabled(true);
                    this.jTextArea1.setText(state);

                }
                else if(verify==7)
                {
                    sendData_GET(6);
                }
            }
            else {
                this.systemButton.setEnabled(false);
                this.arpButton.setEnabled(false);
                this.udpButton.setEnabled(false);
                this.tcpButton.setEnabled(false);
            }
                
                
        } catch (Exception e) {
            e.printStackTrace();
            if(verify ==2)
                this.stateOfVerfiy2.setText("Faild: exception");
            else
                this.stateOfVerfiy1.setText("Faild: exception");

        }

    }
    
    
    
    
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HW_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HW_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HW_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HW_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HW_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IdText;
    private javax.swing.JButton arpButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField passwordText;
    private javax.swing.JLabel stateOfVerfiy1;
    private javax.swing.JLabel stateOfVerfiy2;
    private javax.swing.JTextField sysContactText;
    private javax.swing.JTextField sysLocationText;
    private javax.swing.JTextField sysNameText;
    private javax.swing.JButton systemButton;
    private javax.swing.JButton tcpButton;
    private javax.swing.JButton udpButton;
    private javax.swing.JButton updateButton;
    private javax.swing.JTextField usernameText;
    private javax.swing.JButton verfiy1Button;
    private javax.swing.JButton verfiy2Button;
    // End of variables declaration//GEN-END:variables
}
